# Generated by Django 4.2.7 on 2023-11-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_invite_code_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
