# Generated by Django 4.2.7 on 2023-11-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_invite_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='user',
            name='invited_by',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
